package dialects

import (
	"fmt"

	"github.com/pressly/goose/v3/database/dialect"
)

// NewDuckDB returns a new [dialect.Querier] for DuckDB dialect.
//
// DuckDB does not support AUTOINCREMENT or GENERATED BY DEFAULT AS IDENTITY,
// so we use explicit SEQUENCE creation for auto-incrementing IDs.
// See https://github.com/pressly/goose/issues/1010
func NewDuckDB() dialect.Querier {
	return &duckdb{}
}

type duckdb struct{}

var _ dialect.Querier = (*duckdb)(nil)

func (d *duckdb) CreateTable(tableName string) string {
	// DuckDB requires explicit SEQUENCE for auto-incrementing IDs.
	// The sequence name is derived from the table name to avoid conflicts.
	seqName := tableName + "_id_seq"
	q := `CREATE SEQUENCE IF NOT EXISTS %s START 1;
CREATE TABLE %s (
	id INTEGER PRIMARY KEY DEFAULT nextval('%s'),
	version_id BIGINT NOT NULL,
	is_applied BOOLEAN NOT NULL,
	tstamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)`
	return fmt.Sprintf(q, seqName, tableName, seqName)
}

func (d *duckdb) InsertVersion(tableName string) string {
	q := `INSERT INTO %s (version_id, is_applied) VALUES ($1, $2)`
	return fmt.Sprintf(q, tableName)
}

func (d *duckdb) DeleteVersion(tableName string) string {
	q := `DELETE FROM %s WHERE version_id=$1`
	return fmt.Sprintf(q, tableName)
}

func (d *duckdb) GetMigrationByVersion(tableName string) string {
	q := `SELECT tstamp, is_applied FROM %s WHERE version_id=$1 ORDER BY tstamp DESC LIMIT 1`
	return fmt.Sprintf(q, tableName)
}

func (d *duckdb) ListMigrations(tableName string) string {
	q := `SELECT version_id, is_applied FROM %s ORDER BY id DESC`
	return fmt.Sprintf(q, tableName)
}

func (d *duckdb) GetLatestVersion(tableName string) string {
	q := `SELECT MAX(version_id) FROM %s`
	return fmt.Sprintf(q, tableName)
}
