package dialects

import (
	"fmt"
	"strings"

	"github.com/pressly/goose/v3/database/dialect"
)

// NewOracle returns a new [dialect.Querier] for Oracle dialect.
func NewOracle() dialect.QuerierExtender {
	return &oracle{}
}

type oracle struct{}

var _ dialect.QuerierExtender = (*oracle)(nil)

func (o *oracle) CreateTable(tableName string) string {
	q := `CREATE TABLE %s (
		id NUMBER GENERATED BY DEFAULT AS IDENTITY,
		version_id NUMBER(19) NOT NULL,
		is_applied NUMBER(1) NOT NULL,
		tstamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
		PRIMARY KEY(id)
	)`
	return fmt.Sprintf(q, tableName)
}

func (o *oracle) InsertVersion(tableName string) string {
	q := `INSERT INTO %s (version_id, is_applied) VALUES (:1, :2)`
	return fmt.Sprintf(q, tableName)
}

func (o *oracle) DeleteVersion(tableName string) string {
	q := `DELETE FROM %s WHERE version_id = :1`
	return fmt.Sprintf(q, tableName)
}

func (o *oracle) GetMigrationByVersion(tableName string) string {
	q := `SELECT tstamp, is_applied FROM %s WHERE version_id = :1 ORDER BY tstamp DESC FETCH FIRST 1 ROWS ONLY`
	return fmt.Sprintf(q, tableName)
}

func (o *oracle) ListMigrations(tableName string) string {
	q := `SELECT version_id, is_applied FROM %s ORDER BY id DESC`
	return fmt.Sprintf(q, tableName)
}

func (o *oracle) GetLatestVersion(tableName string) string {
	q := `SELECT MAX(version_id) FROM %s`
	return fmt.Sprintf(q, tableName)
}

func (o *oracle) TableExists(tableName string) string {
	schemaName, tableName := parseOracleTableIdentifier(tableName)
	if schemaName != "" {
		q := `SELECT CASE WHEN EXISTS (SELECT 1 FROM all_tables WHERE owner = '%s' AND table_name = '%s') THEN 1 ELSE 0 END FROM dual`
		return fmt.Sprintf(q, strings.ToUpper(schemaName), strings.ToUpper(tableName))
	}
	q := `SELECT CASE WHEN EXISTS (SELECT 1 FROM user_tables WHERE table_name = '%s') THEN 1 ELSE 0 END FROM dual`
	return fmt.Sprintf(q, strings.ToUpper(tableName))
}

func parseOracleTableIdentifier(name string) (schema, table string) {
	schema, table, found := strings.Cut(name, ".")
	if !found {
		return "", name
	}
	return schema, table
}
