version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    assignees:
      - "mfridman"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      gomod:
        patterns:
          - "*"
    assignees:
      - "mfridman"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
