stages:
  - build
  - test
  - images

variables:
  GO_IMAGE: golang:1.20
  DOCKER_VERSION: "20.10.21"
  DOCKER_IMAGE_REGISTRY: registry.gitlab.com/gitlab-org/opstrace/goose
  ## runner feature flag to try and speed up cache zipping - https://docs.gitlab.com/runner/configuration/feature-flags.html
  FF_USE_FASTZIP: "true"
  # compression levels set to fast (larger cache files)
  ARTIFACT_COMPRESSION_LEVEL: "fast"
  CACHE_COMPRESSION_LEVEL: "fast"

default:
  image: $GO_IMAGE

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    key:
      files:
        - go.sum
    paths:
      - .go/pkg/mod/

#lint:
#  stage: test
#  extends: .go-cache
#  script:
#    - make lint

build:
  stage: build
  extends: .go-cache
  script:
    - make build

test:
  stage: test
  extends: .go-cache
  script:
    - make test-packages

#images:
#  stage: images
#  extends:
#    - .docker
#  script:
#    - make docker docker-push
#  variables:
#    DOCKER_REPO: $DOCKER_IMAGE_REGISTRY
#    DOCKER_TAG:  $CI_COMMIT_SHORT_SHA
#  needs: [test]
#  cache: []

e2e-test:
  stage: test
  image: $GO_IMAGE
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DB_HOST: "docker"
  services:
    - name: docker:${DOCKER_VERSION}-dind
      # explicitly disable tls to avoid docker startup interruption
      command: ["--tls=false"]
  tags:
    - gitlab-org-docker
  extends:
    - .go-cache
  script:
    - make test-e2e-clickhouse

.docker:
  image: docker:${DOCKER_VERSION}-git
  services:
    - name: docker:${DOCKER_VERSION}-dind
      # explicitly disable tls to avoid docker startup interruption
      command: ["--tls=false"]
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  tags:
    - gitlab-org-docker
  before_script:
    - apk add --no-cache make bash
    - echo "${CI_REGISTRY_PASSWORD}" | docker login --username "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"