name: Goose end-end tests

on:
  push:
    branches:
      - master
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run e2e tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        dialect: ["postgres", "mysql", "vertica", "clickhouse", "ydb", "turso"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Run e2e ${{ matrix.dialect }} tests
        run: |
          make test-e2e-${{ matrix.dialect }}
