name: Goose end-end tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run e2e tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        dialect: ["postgres", "mysql", "vertica", "clickhouse", "ydb"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Run e2e ${{ matrix.dialect }} tests
        run: |
          make test-e2e-${{ matrix.dialect }}
