name: Goose end-end tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run e2e tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        dialect: ["postgres", "mysql", "vertica", "clickhouse"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.x"
          check-latest: true
          cache: true
      - name: Run e2e ${{ matrix.dialect }} tests
        run: |
          make test-e2e-${{ matrix.dialect }}
